CREATE TABLE clientes (
    id        NUMBER(10) NOT NULL,
    nombre    VARCHAR2(20 BYTE) NOT NULL,
    apellido  VARCHAR2(20 BYTE) NOT NULL,
    rut       VARCHAR2(12 BYTE) NOT NULL,
    ciudad    VARCHAR2(30 BYTE) NOT NULL,
    edad      NUMBER(3) NOT NULL
);

ALTER TABLE clientes ADD (
  CONSTRAINT id_pk PRIMARY KEY (id));

CREATE SEQUENCE id_seq START WITH 1 INCREMENT BY 1;

CREATE TRIGGER id_clientes_tri
BEFORE INSERT ON clientes
FOR EACH ROW
BEGIN
SELECT id_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
    
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Pedro', 'Gonzalez', '12.282.938-4', 'Temuco', 29);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Francisco', 'Perez', '23.232.218-4', 'Valdivia', 22);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Roberto', 'Tapia', '12.211.568-K', 'Osorno', 39);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Felipe', 'Fernandez', '16.342.118-4', 'Santiago', 33);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Pia', 'Martinez', '13.523.123-6', 'Rancagua', 48);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Jesus', 'Villalba', '17.112.423-4', 'Santa Cruz', 12);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Pastor', 'Gutierrez', '13.922.111-2', 'Valparaiso', 84);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Pascal', 'Perez', '17.125.242-8', 'La Serena', 34);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Jose', 'Castro', '15.923.843-1', 'Villarrica', 59);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Maria', 'Espinoza', '18.493.128-0', 'Pucon', 82);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Isaac', 'Castillo', '11.124.582-3', 'Temuco', 28);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Ana', 'Salas', '10.129.384-2', 'Valdivia', 21);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Santo', 'Vidal', '18.343.282-8', 'Osorno', 17);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Piera', 'Contreras', '5.223.929-3', 'Santiago', 18);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Pietro', 'Lizarraga', '8.192.232-K', 'Rancagua', 82);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Osvaldo', 'Pedernera', '5.128.321-1', 'Valparaiso', 88);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Julio', 'Cuadrado', '7.291.772-8', 'Viña del mar', 37);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Priscila', 'Hermosilla', '4.383.363-7', 'Coquimbo', 30);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Adrian', 'Marquina', '14.293.869-3', 'Antofagasta', 27);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Adolfo', 'Hitler', '16.934.839-1', 'Arica', 38);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, RUT, CIUDAD, EDAD) VALUES ('Rodolfo', 'Soler', '18.823.372-7', 'Puerto Montt', 42);